baseURL: https://bginger.art/
title: GINGER
defaultContentLanguage: "en"
theme: eternity
googleAnalytics: "G-974WD1S4FM"

params:
  image: /images/banner.png
  logo: logo.png
  subtitle: Ginger's portfolio
  copyright: All rights reserved.
  author: Ginger Chiang
  dontShowSource: true
  portfolio:
    columns:
      desktop:
        nature: 4
        archive: 6
        people: 2
        default: 3
      mobile:
        default: 2
        archive: 3
        people: 1
  socials:
    - icon: "far fa-envelope fa-lg"
      url: "mailto:comingmissing@gmail.com"
      title: "email"
      landing: true
    # - icon: 'fab fa-github fa-lg'
    #   url: 'https://github.com/boratanrikulu/eternity'
    #   landing: true
    # - icon: 'fab fa-instagram fa-lg'
    #   url: 'https://instagram.bora.sh/eternity'
    # - icon: 'fab fa-linkedin-in fa-lg'
    #   url: 'https://linkedin.bora.sh/in/eternity'
  homepage: "/about" # homepage link, mostly same with menu.main[0]
  specialPages:
    - about
    - archive
  bypassWelcomePage: true # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: false # disables the background image on the homepage
  plausible: "" # todo: set your plausible id.
  disableRadius: false
  moveIt: false # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  about: ":contentbasename/"

menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: 動畫
      url: /tags/motion-graphic/
      weight: 2
    - name: 資訊圖表
      url: /tags/infographics/
      weight: 3
    - name: 平面設計
      url: /tags/graphic-design/
      weight: 4
    - name: 一圖看懂
      url: /tags/one-picture/
      weight: 5
    - name: 插畫
      url: /tags/digital-drawing/
      weight: 6
    - name: 商品設計
      url: /tags/product-design/
      weight: 7
    - name: 網頁設計
      url: /tags/web-design/
      weight: 8
    # - name: tags
    #   url: /tags/
    #   weight: 9
    # - name: archive
    #   url: /tags/archive/
    #   weight: 10
